#!/usr/bin/env python3
"""Generate `docs/contract-inventory.md` from the canonical ODCS contracts.

Reads every `references/odcs/pc/**/*.odcs.yaml` (excluding the `templates/`
folder) and writes a single navigation page surfacing kind, subject area,
version, status, one-line description, and ADR back-links for every contract.

The generator is idempotent: rerunning against an unchanged tree produces no
diff. The kind heuristic and the codeset → `silver_reference_data` schema rule
mirror `scripts/generation/generate-fabric-manifests.py`.
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
CONTRACT_GLOB = "references/odcs/pc/**/*.odcs.yaml"
OUTPUT_PATH = ROOT / "docs" / "contract-inventory.md"

EVENT_SLUG_SUFFIX = "-lifecycle-event"
TRANSACTION_SLUG_SUFFIX = "-transaction"
TRANSACTION_EXACT_SLUGS = {
    "financial-transaction",
    "policy-financial-transaction",
    "claim-financial-transaction",
}

REFERENCE_DATA_SCHEMA = "silver_reference_data"

# Display order for schemas (matches FABRIC_IMPLEMENTATION_PLAN.md §4 and the
# F3 closeout note that codesets land under silver_reference_data regardless of
# their canonical subjectArea).
SCHEMA_DISPLAY_ORDER = (
    "silver_core",
    "silver_policy",
    "silver_coverage",
    "silver_product",
    "silver_exposure",
    "silver_submission",
    "silver_claims",
    "silver_financial",
    "silver_reference_data",
)

# Display order for kinds.
KIND_DISPLAY_ORDER = ("entity", "event", "transaction", "codeset")

GENERATED_BANNER = (
    "<!-- generated by scripts/generation/generate-contract-inventory.py;"
    " do not edit by hand. Rerun the script after changing any contract. -->"
)


class Contract:
    """Light-weight contract record used by the inventory generator."""

    __slots__ = (
        "path",
        "slug",
        "id",
        "name",
        "version",
        "status",
        "description",
        "subject_area",
        "kind",
        "schema",
        "adrs",
    )

    def __init__(self, path: Path, data: dict[str, Any]) -> None:
        self.path = path
        self.slug = path.name.removesuffix(".odcs.yaml")
        self.id = str(data.get("id", "")).strip()
        self.name = str(data.get("name", "")).strip()
        self.version = str(data.get("version", "")).strip()
        self.status = str(data.get("status", "")).strip()
        self.description = _first_sentence(str(data.get("description", "")))
        custom = data.get("customProperties") or {}
        if not isinstance(custom, dict):
            custom = {}
        self.subject_area = str(custom.get("subjectArea", "")).strip()
        self.adrs = _normalize_adrs(custom.get("adrs"))
        self.kind = _derive_kind(path, self.slug)
        self.schema = _derive_schema(path, self.subject_area)


def _first_sentence(description: str) -> str:
    """Return the first sentence of a description, with a trailing period.

    Splits on a literal '. ' boundary so abbreviations inside the first
    sentence (e.g. 'P&C' followed by lowercase) do not split prematurely. Falls
    back to the full string when no sentence boundary is found.
    """

    text = description.strip()
    if not text:
        return ""
    cut = text.find(". ")
    if cut == -1:
        return text if text.endswith(".") else text + "."
    return text[: cut + 1]


def _normalize_adrs(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _derive_kind(path: Path, slug: str) -> str:
    if path.parent.name == "reference-data":
        return "codeset"
    if slug.endswith(EVENT_SLUG_SUFFIX):
        return "event"
    if slug.endswith(TRANSACTION_SLUG_SUFFIX) or slug in TRANSACTION_EXACT_SLUGS:
        return "transaction"
    return "entity"


def _derive_schema(path: Path, subject_area: str) -> str:
    if path.parent.name == "reference-data":
        return REFERENCE_DATA_SCHEMA
    if subject_area:
        return f"silver_{subject_area.replace('-', '_')}"
    return "silver_unknown"


def load_contracts() -> list[Contract]:
    contracts: list[Contract] = []
    for path in sorted(ROOT.glob(CONTRACT_GLOB)):
        if "templates" in path.parts:
            continue
        with path.open(encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
        if not isinstance(data, dict):
            continue
        contracts.append(Contract(path, data))
    contracts.sort(key=lambda c: (c.schema, c.id))
    return contracts


# ---------------------------------------------------------------------------
# Markdown rendering.
# ---------------------------------------------------------------------------


def render(contracts: list[Contract]) -> str:
    parts: list[str] = []
    parts.append(GENERATED_BANNER)
    parts.append("")
    parts.append("# Contract Inventory")
    parts.append("")
    parts.append(
        "This page is the navigation surface for every canonical ODCS contract"
        " under `references/odcs/pc/`. It is generated from the contract files"
        " by `scripts/generation/generate-contract-inventory.py` and cannot be"
        " hand-edited."
    )
    parts.append("")
    parts.append(
        "Counts and status reflect the current `references/odcs/` tree."
        " Versions follow `references/design-decisions/pc/versioning-policy.md`."
        " Status promotion gates live in"
        " `references/design-decisions/pc/status-promotion.md`."
    )
    parts.append("")

    parts.extend(_render_counts(contracts))
    parts.append("")
    parts.extend(_render_by_schema(contracts))
    parts.append("")
    parts.extend(_render_by_kind(contracts))
    parts.append("")
    parts.extend(_render_appendix(contracts))
    parts.append("")
    return "\n".join(parts)


def _render_counts(contracts: list[Contract]) -> list[str]:
    by_kind = Counter(c.kind for c in contracts)
    by_schema = Counter(c.schema for c in contracts)
    by_status = Counter(c.status or "(unset)" for c in contracts)
    by_version = Counter(c.version or "(unset)" for c in contracts)

    out = ["## 1. Counts at a glance", "", f"**Total contracts:** {len(contracts)}", ""]
    out.append("**By kind:**")
    out.append("")
    out.append("| Kind | Count |")
    out.append("|---|---|")
    for kind in KIND_DISPLAY_ORDER:
        if by_kind.get(kind):
            out.append(f"| {kind} | {by_kind[kind]} |")
    leftover_kinds = sorted(k for k in by_kind if k not in KIND_DISPLAY_ORDER)
    for kind in leftover_kinds:
        out.append(f"| {kind} | {by_kind[kind]} |")
    out.append("")

    out.append("**By Spark schema:**")
    out.append("")
    out.append("| Schema | Count |")
    out.append("|---|---|")
    for schema in SCHEMA_DISPLAY_ORDER:
        if by_schema.get(schema):
            out.append(f"| `{schema}` | {by_schema[schema]} |")
    leftover_schemas = sorted(s for s in by_schema if s not in SCHEMA_DISPLAY_ORDER)
    for schema in leftover_schemas:
        out.append(f"| `{schema}` | {by_schema[schema]} |")
    out.append("")

    out.append("**By status:**")
    out.append("")
    out.append("| Status | Count |")
    out.append("|---|---|")
    for status in sorted(by_status):
        out.append(f"| {status} | {by_status[status]} |")
    out.append("")

    out.append("**By version:**")
    out.append("")
    out.append("| Version | Count |")
    out.append("|---|---|")
    for version in sorted(by_version):
        out.append(f"| {version} | {by_version[version]} |")
    return out


def _render_by_schema(contracts: list[Contract]) -> list[str]:
    grouped: dict[str, list[Contract]] = defaultdict(list)
    for contract in contracts:
        grouped[contract.schema].append(contract)

    out = [
        "## 2. By Spark schema (subject area)",
        "",
        "Contracts are grouped by the Lakehouse schema they materialize into."
        " The codesets all land in `silver_reference_data` per the F3 closeout"
        " decision, even though their canonical `subjectArea` may be claims,"
        " policy, financial, or another domain.",
    ]
    out.append("")

    schema_order = list(SCHEMA_DISPLAY_ORDER) + sorted(
        s for s in grouped if s not in SCHEMA_DISPLAY_ORDER
    )
    for schema in schema_order:
        rows = grouped.get(schema)
        if not rows:
            continue
        out.append(f"### `{schema}` ({len(rows)})")
        out.append("")
        out.append("| Contract id | Name | Kind | Version | Status | Description | ADRs |")
        out.append("|---|---|---|---|---|---|---|")
        for c in rows:
            out.append(
                f"| `{c.id}` | {c.name} | {c.kind} | {c.version} | {c.status} |"
                f" {_md_inline(c.description)} | {_format_adrs(c.adrs)} |"
            )
        out.append("")
    return out


def _render_by_kind(contracts: list[Contract]) -> list[str]:
    grouped: dict[str, list[Contract]] = defaultdict(list)
    for contract in contracts:
        grouped[contract.kind].append(contract)

    out = [
        "## 3. By contract kind",
        "",
        "The same set partitioned by materialization shape. Entity and codeset"
        " contracts are SCD2-merged; event and transaction contracts are"
        " append-only with `correction_indicator` semantics. The cross-cutting"
        " ADR is `references/design-decisions/pc/event-and-transaction.md`.",
    ]
    out.append("")

    for kind in KIND_DISPLAY_ORDER:
        rows = grouped.get(kind)
        if not rows:
            continue
        rows_sorted = sorted(rows, key=lambda c: c.id)
        out.append(f"### {kind} ({len(rows_sorted)})")
        out.append("")
        out.append("| Contract id | Name | Schema | Version | Status | Description |")
        out.append("|---|---|---|---|---|---|")
        for c in rows_sorted:
            out.append(
                f"| `{c.id}` | {c.name} | `{c.schema}` | {c.version} | {c.status} |"
                f" {_md_inline(c.description)} |"
            )
        out.append("")
    return out


def _render_appendix(contracts: list[Contract]) -> list[str]:
    out = [
        "## 4. Source path appendix",
        "",
        "Every contract id maps to a tracked YAML file under `references/odcs/pc/`.",
        "",
        "| Contract id | Source path |",
        "|---|---|",
    ]
    for c in sorted(contracts, key=lambda c: c.id):
        rel = c.path.relative_to(ROOT).as_posix()
        out.append(f"| `{c.id}` | `{rel}` |")
    return out


def _md_inline(text: str) -> str:
    """Escape pipes and collapse newlines for use inside a markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _format_adrs(adrs: list[str]) -> str:
    if not adrs:
        return "—"
    return ", ".join(f"`{name}`" for name in adrs)


# ---------------------------------------------------------------------------
# Entry point.
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    check = "--check" in argv
    contracts = load_contracts()
    if not contracts:
        print("No contracts found", file=sys.stderr)
        return 1
    rendered = render(contracts)
    if check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run without --check first.", file=sys.stderr)
            return 1
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"{OUTPUT_PATH} is out of date with the canonical contract surface."
                " Rerun scripts/generation/generate-contract-inventory.py.",
                file=sys.stderr,
            )
            return 1
        print(f"Inventory at {OUTPUT_PATH.relative_to(ROOT)} is up to date.")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    by_kind = Counter(c.kind for c in contracts)
    by_schema = Counter(c.schema for c in contracts)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}: {len(contracts)} contracts")
    print(
        "  by kind: "
        + ", ".join(f"{k}={by_kind[k]}" for k in KIND_DISPLAY_ORDER if by_kind.get(k))
    )
    print(
        "  by schema: "
        + ", ".join(
            f"{s}={by_schema[s]}" for s in SCHEMA_DISPLAY_ORDER if by_schema.get(s)
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
