#!/usr/bin/env python3
"""Generate the repository-level `CHANGELOG.md` from per-contract changelogs.

Reads every `references/odcs/pc/**/*.odcs.yaml` (excluding the `templates/`
folder), parses each contract's `customProperties.changelog` array, and emits
a single Markdown file at the repository root grouping entries by
canonical-version wave (`0.4.x` → `0.1.x`, newest first).

The generator does **not** consult git history; the source of truth for what
changed in each wave is the contract's own changelog entries. Per
`MILESTONE_10_PLAN.md` §4 (M10.3), if a future milestone wants release-notes
that draw on commit messages or PR titles, that is a separate generator.

Each per-contract entry follows the convention used since the C3 hardening
wave: `'<version>: <summary> [(<author>, <YYYY-MM-DD>)]'`. The trailing
`(author, date)` parenthetical is optional. Entries that do not match are
emitted with `—` in the date column and `(parse failed)` appended to the
summary so malformed entries are surfaced rather than hidden.
"""

from __future__ import annotations

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, NamedTuple

import yaml

ROOT = Path(__file__).resolve().parents[2]
CONTRACT_GLOB = "references/odcs/pc/**/*.odcs.yaml"
OUTPUT_PATH = ROOT / "CHANGELOG.md"

GENERATED_BANNER = (
    "<!-- generated by scripts/generation/generate-changelog.py;"
    " do not edit by hand. Rerun the script after changing any contract. -->"
)

VERSION_RE = re.compile(r"^(?P<version>\d+\.\d+\.\d+):\s*(?P<rest>.*)$", re.DOTALL)
TRAILING_DATE_RE = re.compile(
    r"\s*\((?P<author>[^,()]+),\s*(?P<date>\d{4}-\d{2}-\d{2})\)\.?\s*$"
)


class Entry(NamedTuple):
    contract_id: str
    contract_name: str
    version: str
    wave: str
    summary: str
    date: str

    @property
    def sort_key(self) -> tuple[tuple[int, ...], str]:
        try:
            parts = tuple(int(part) for part in self.version.split("."))
        except ValueError:
            parts = (0,)
        return (parts, self.contract_id)


def parse_changelog_entry(raw: str, contract_id: str, contract_name: str) -> Entry:
    """Parse one changelog string into an Entry."""

    text = " ".join(raw.split())  # collapse internal whitespace and folded newlines
    match = VERSION_RE.match(text)
    if not match:
        return Entry(
            contract_id=contract_id,
            contract_name=contract_name,
            version="0.0.0",
            wave="(unparsed)",
            summary=f"{text} (parse failed)",
            date="—",
        )
    version = match.group("version")
    rest = match.group("rest").strip()
    date = "—"
    trailing = TRAILING_DATE_RE.search(rest)
    if trailing:
        date = trailing.group("date")
        rest = rest[: trailing.start()].rstrip()
    if rest.endswith(".") and rest.count(".") == 1 and len(rest) < 4:
        # Recovered an empty summary like "0.1.0: ." — still valid, leave it.
        pass
    wave = ".".join(version.split(".")[:2]) + ".x"
    return Entry(
        contract_id=contract_id,
        contract_name=contract_name,
        version=version,
        wave=wave,
        summary=rest,
        date=date,
    )


def load_entries() -> list[Entry]:
    entries: list[Entry] = []
    for path in sorted(ROOT.glob(CONTRACT_GLOB)):
        if "templates" in path.parts:
            continue
        with path.open(encoding="utf-8") as handle:
            data: Any = yaml.safe_load(handle)
        if not isinstance(data, dict):
            continue
        contract_id = str(data.get("id", "")).strip()
        contract_name = str(data.get("name", "")).strip()
        custom = data.get("customProperties") or {}
        if not isinstance(custom, dict):
            continue
        changelog = custom.get("changelog") or []
        if not isinstance(changelog, list):
            continue
        for raw in changelog:
            if not isinstance(raw, str):
                continue
            entries.append(parse_changelog_entry(raw, contract_id, contract_name))
    return entries


def render(entries: list[Entry]) -> str:
    parts: list[str] = []
    parts.append(GENERATED_BANNER)
    parts.append("")
    parts.append("# Changelog")
    parts.append("")
    parts.append(
        "Repository-level changelog aggregating every per-contract"
        " `customProperties.changelog` entry across the canonical surface under"
        " `references/odcs/pc/`."
    )
    parts.append("")
    parts.append(
        "Entries are grouped by canonical-version **wave** (`MAJOR.MINOR.x`),"
        " newest wave first. Within a wave, rows are sorted by version"
        " descending and then contract id ascending. The wave grouping mirrors"
        " how each canonical hardening / Fabric milestone shipped: see"
        " `planning-mds/STATUS.md` and `planning-mds/IMPLEMENTATION_PLAN.md`"
        " for the milestone-by-milestone breakdown."
    )
    parts.append("")
    parts.append(
        "Generated by `scripts/generation/generate-changelog.py`; rerun after"
        " any contract version bump. Do not edit this file by hand."
    )
    parts.append("")
    parts.extend(_render_summary(entries))
    parts.append("")
    parts.extend(_render_waves(entries))
    parts.append("")
    parts.extend(_render_footer())
    parts.append("")
    return "\n".join(parts)


def _render_summary(entries: list[Entry]) -> list[str]:
    by_wave = Counter(entry.wave for entry in entries)
    out = ["## Summary", "", "| Wave | Entries |", "|---|---|"]
    for wave in _ordered_waves(entries):
        out.append(f"| `{wave}` | {by_wave[wave]} |")
    out.append(f"| **Total** | **{len(entries)}** |")
    return out


def _render_waves(entries: list[Entry]) -> list[str]:
    grouped: dict[str, list[Entry]] = defaultdict(list)
    for entry in entries:
        grouped[entry.wave].append(entry)
    out: list[str] = []
    for wave in _ordered_waves(entries):
        rows = sorted(
            grouped[wave],
            key=lambda e: (
                tuple(-int(part) for part in e.version.split(".")) if e.version != "0.0.0" else (0,),
                e.contract_id,
            ),
        )
        out.append(f"## Wave `{wave}` ({len(rows)} entries)")
        out.append("")
        out.append("| Contract id | Name | Version | Date | Summary |")
        out.append("|---|---|---|---|---|")
        for entry in rows:
            out.append(
                f"| `{entry.contract_id}` | {entry.contract_name} |"
                f" {entry.version} | {entry.date} | {_md_inline(entry.summary)} |"
            )
        out.append("")
    return out


def _render_footer() -> list[str]:
    return [
        "## How to read this file",
        "",
        "- **Wave** — the canonical-version family the entry belongs to (`0.4.x`,"
        " `0.3.x`, `0.2.x`, `0.1.x`). Each wave corresponds to a milestone or"
        " hardening phase. The 0.1.x wave is the original ship state for each"
        " contract; 0.2.0 is the W015 cross-cutting ADR refactor; 0.3.0 is the"
        " C3 bulk hardening refactor; 0.4.0 is the C4 entity-gap closure;"
        " 0.4.1 / 0.4.2 are the C5 / C7 single-contract cleanups.",
        "- **Date** — when the entry was authored, when the per-contract"
        " changelog string carries an `(author, YYYY-MM-DD)` parenthetical."
        " Older entries omit the date; the column shows `—` in that case.",
        "- **Summary** — the per-contract changelog text verbatim, with the"
        " leading `<version>:` token stripped and any trailing `(author, date)`"
        " parenthetical lifted into the **Date** column.",
        "",
        "Versioning rules: `references/design-decisions/pc/versioning-policy.md`."
        " Status promotion gates: `references/design-decisions/pc/status-promotion.md`.",
    ]


def _ordered_waves(entries: list[Entry]) -> list[str]:
    waves = {entry.wave for entry in entries if entry.wave != "(unparsed)"}

    def wave_key(wave: str) -> tuple[int, ...]:
        major, minor, _ = wave.split(".")
        return (int(major), int(minor))

    ordered = sorted(waves, key=wave_key, reverse=True)
    if any(entry.wave == "(unparsed)" for entry in entries):
        ordered.append("(unparsed)")
    return ordered


def _md_inline(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def main(argv: list[str]) -> int:
    check = "--check" in argv
    entries = load_entries()
    if not entries:
        print("No changelog entries found", file=sys.stderr)
        return 1
    rendered = render(entries)
    if check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run without --check first.", file=sys.stderr)
            return 1
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"{OUTPUT_PATH} is out of date with the canonical contract surface."
                " Rerun scripts/generation/generate-changelog.py.",
                file=sys.stderr,
            )
            return 1
        print(f"Changelog at {OUTPUT_PATH.relative_to(ROOT)} is up to date.")
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    by_wave = Counter(entry.wave for entry in entries)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}: {len(entries)} entries")
    for wave in _ordered_waves(entries):
        print(f"  {wave}: {by_wave[wave]}")
    unparsed = sum(1 for entry in entries if entry.wave == "(unparsed)")
    if unparsed:
        print(
            f"Warning: {unparsed} entries failed to parse;"
            " surfaced under the (unparsed) wave for reviewer attention.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
